name: Docs

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v2

      - name: Use Node 14.x 🔧
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install deps and build (with cache) 📦
        uses: bahmutov/npm-install@v1

      - name: Build Project 🚧
        run: |
          yarn build

      - name: Install deps and build (with cache) 📦
        uses: bahmutov/npm-install@v1
        with:
          working-directory: website

      - name: Test Build 🚧
        run: |
          pushd website
          yarn build
          popd

  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v2

      - name: Use Node 14.x 🔧
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Setup SSH Keys 🔑
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}

      - name: Install deps and build (with cache) 📦
        uses: bahmutov/npm-install@v1

      - name: Build Project 🚧
        run: |
          yarn build

      - name: Install deps and build (with cache) 📦
        uses: bahmutov/npm-install@v1
        with:
          working-directory: website

      - name: Release to GitHub Pages 🚀
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: gh-pages

        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          pushd website
          yarn deploy
          popd
